#! /bin/sh
# for licensing information see file LICENSE

category=""
if [ "$#" -eq "1" ]; then
	package="$1"
elif [ "$#" -eq "2" ]; then
	package="$1"
	category="$2"
else
	echo -e "Usage:\nxie PACKAGE [CATEGORY]"
	exit 1
fi

_all_results="$(eix -# "$package" -C "$category")"

# get weighted history
_hist="$(sort ~/.xie_history | uniq -c | sort -nr | awk '{print $2}' | grep -F $package)"
_all_wo_hist="$((echo "$_all_results"; echo "$_hist"; echo "$_hist") | sort | uniq -u)"
_all="$((echo "$_hist"; echo "$_all_wo_hist") | sed '/^$/d')"

if [ "$(echo "$_all" | wc -l)" -eq "1" ]; then
	_result="$_all"
else
	_result="$(echo -n "$_all" | dmenu -i -l 10)"
	if [ "$?" -ne "0" ]; then
		exit 1;
	fi
fi

eix -v -e "$_result" && echo "$_result" >> ~/.xie_history
